home/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.sebuah_fungsi, name='sebuah_fungsi')
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls')),
    path('home/', include('home.urls')),
    path('', include('django.contrib.auth.urls'))
]

story9/urls.py
from os import name
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.awal, name='awal'),
    path('register/', views.register, name='register'),
]

home/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

home/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.

def index(request):
    return render(request, 'index.html')

def sebuah_fungsi(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    urlm = requests.get(url)
    data = json.loads(urlm.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def awal(request):
    return render(request, 'awal.html')

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')  
    else:
        form = UserCreationForm()
    return render(request, 'reg.html', {'form' : form})
    

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
<link rel="stylesheet" href="{% static 'style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}
{% block content %}    
      <br>
      <br>
      <br>
      <br>
      <input class="form-control" style="width: 50%;margin: auto;" id="keyword" placeholder="Search..">
      <br>
      <table class="table table-borderless" style="width: 75%; margin: auto;background-color: gainsboro;" id="daftar_buku">  
        
      </table>
      <script type="text/javascript">
        $( document ).ready(function() {
          console.log( "ready!" );
          var head = "<thead> <tr> <th> No </th> <th> Judul </th> <th> Penulis </th> <th> Sampul </th> </tr> </thead>"
          $("#daftar_buku").append(head);
          var defa = "Batavia"
          $.ajax({
            url: 'data?q=' + defa,
            success: function(data) {
            var arr = data.items;
            for (i = 0; i < arr.length; i++) {
                  judul = arr[i].volumeInfo.title;
                  penulis = arr[i].volumeInfo.authors;
                  sampul = arr[i].volumeInfo.imageLinks.smallThumbnail;
                  console.log(judul);
                  console.log(penulis);
                  console.log(sampul);
                  var j = i+1;
                  $("#daftar_buku").append("<tr> <td>" + j + " <td>" + judul + "</td> <td>" + penulis + "</td> <td> <img src=" + sampul + "></td> </tr>" );
                }

            }
          })
        });
        $("#keyword").keyup(function(){
          var item = $("#keyword").val(); 
          console.log(item);
          $.ajax({
            url: 'data?q=' + item,
            success: function(data) {
              console.log(data);
              var arr = data.items;
              var head = "<thead> <tr> <th> No </th> <th> Judul </th> <th> Penulis </th> <th> Sampul </th> </tr> </thead>"
              $("#daftar_buku").empty();
              $("#daftar_buku").append(head);
              // console.log(arr);
              for (i = 0; i < arr.length; i++) {
                judul = arr[i].volumeInfo.title;
                penulis = arr[i].volumeInfo.authors;
                sampul = arr[i].volumeInfo.imageLinks.smallThumbnail;
                console.log(judul);
                console.log(penulis);
                console.log(sampul);
                var j = i+1;
                $("#daftar_buku").append("<tr> <td>" + j + " <td>" + judul + "</td> <td>" + penulis + "</td> <td> <img src=" + sampul + "></td> </tr>" );
              }
            }
          })
        });
      </script>
{% endblock content %}

story9/templates/awal.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
<link rel="stylesheet" href="{% static 'style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}
{% block content %}
<br>
<br>    
<br>
<br>
{% if user.is_authenticated %}
<div class="text-center" style="background-color: lightgrey;width: 50%;margin: auto;border-radius: 25px;padding: 20px;">
    <h1>Hi {{user}}</h1>
    <a href="/logout"><h3>Logout</h3></a>
</div>
{% else %}
<div class="text-center" style="background-color: lightgrey;width: 50%;margin: auto;border-radius: 25px;padding: 20px;">
      <a href="/login"><h1>LOGIN DULU BOS</h1></a>
</div>
{% endif %}
{% endblock content %}

story9/templates/reg.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
<link rel="stylesheet" href="{% static 'style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% load crispy_forms_tags %}
{% endblock meta %}
{% block content %}
<br>
<br>    
<br>
<br>
<div style="background-color: lightgrey;width: 50%;margin: auto;border-radius: 25px;padding: 20px;">
      <form method="POST" class="form-group">
          {% csrf_token %}
          {{form | crispy}}
          <p>Already have an account? Login <a href="/login">here</a></p>
          <div class = "text-center">
            <button type="submit" class="btn btn-success" >Register</button>
          </div>
      </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-default">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ">
        <a class="nav-link" href="{% url 'home:index' %}">Story 8<span class="sr-only">(current)</span></a>
        <a class="nav-link" href="{% url 'story9:awal' %}">Story 9<span class="sr-only">(current)</span></a>       
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
</body>
  
</html>